[toolchain]
anchor_version = "0.31.1"

[features]
resolution = false
skip-lint = false

[programs.localnet]
clearstone_core = "EKpLcVc6rky1ah28NMZFoT2oSXkAKWcEsr6nbZziTWbC"
generic_exchange_rate_sy = "DZEqpkctMmB1Xq6foy1KnP3VayVFgJfykzi49fpWZ8M6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./testkp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
